language: node_js
node_js: node
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: blbRMunomdwTArKda+BhoMqLqKjF/VD+kd9zjYzi7J9XOtEfhU3D+W0GdY3Bn/kZUk6w0xEw3ngdTCHforXTUnm2hDRb45fyXznCl1LcWYTyl/KgsevRaVaihTkjkrs5U79JqbG9XRXwpaBvXyBcIdC3lkVKzUfK6w3LaByFDmdpLTW3qMwI+1MeXWpXPVWE1CsbuOKWow732qjRMi9MERdzxrtofZXuk8FME2c76txo2hBb6TZauA9Ke+O4TXOwqWEBnPS6uq+eobQUdnbK+yjoUXkftnSAf3l5kuE52NYwCY/wTIboKlXdOmiKV9Apkwsk219FhK9PPmmExJnLI3Fr+O9us0d+YlTfoIlphOEwpCNZS/R6Qg0pMxS9HVNtv1U+zJoYrAZ5v0S/NJkg1f9rMuV2JlBhdVZAs/MZeIYKbuqubUWY/pWsRqqJVTnjJEiwBcaQCR9TjNvPrnmsajiDKyqmthjBeOEYNKFQBVFHkyXyOtCAfs413nyzp9ur5q0eDiht6LX87wB8oudAb97FXdyckwUJpbqhntzVuVupv2ENdDxucagrmQxr3aMhfclzzufvuwDedvBGMcHSn2l3F0Q3xk8O1Y1n7EJ+nvXZkmwe1q3F39IT2PI9DahNYfYn0vGf+Yy9wflsdYzH1/y2bT5yAw5Ra9Aw0ejVaG4=
    app: agile-mountain-17088
  on:
    repo: drzoid14/pantry-manager 